# Generated by Django 6.0.5 on 2026-06-13 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('target_duration', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('script_ready', 'Script ready')], default='script_ready', max_length=32)),
                ('agent1_config', models.JSONField(default=dict)),
                ('agent2_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_key', models.CharField(max_length=16)),
                ('speaker_name', models.CharField(max_length=80)),
                ('speaker_role', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='studio.podcastproject')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'order')},
            },
        ),
    ]
