# Generated by Django 6.0.5 on 2026-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE studio_podcastproject SET status = 'script_ready' WHERE status = 'draft'",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='podcastproject',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('script_ready', 'Script ready'), ('failed', 'Failed')], default='generating', max_length=32),
        ),
    ]
