# Generated by Django 6.0.5 on 2026-06-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_podcastline_id_alter_podcastproject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastline',
            name='used_web_search',
            field=models.BooleanField(default=False),
        ),
    ]
