# Generated by Django 6.0.5 on 2026-06-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_podcastline_used_web_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastproject',
            name='line_delay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
