# Generated by Django 5.2.15 on 2026-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_podcastproject_line_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastproject',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts/'),
        ),
        migrations.AddField(
            model_name='podcastproject',
            name='audio_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='directormessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='podcastline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='podcastproject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
